import * as Icons from "@govtechmy/myds-react/icon";

export const iconDataList = [
  //Generic Icons : 120 icons
  ////////////////////////
  {
    filename: "Icon/outline/placeholder",
    name: "placeholder",
    type: "Generic",
    svg: <Icons.PlaceholderIcon />,
  },
  {
    filename: "Icon/outline/hamburger-menu",
    name: "hamburger-menu",
    type: "Generic",
    svg: <Icons.HamburgerMenuIcon />,
  },
  {
    filename: "Icon/outline/sun",
    name: "sun",
    type: "Generic",
    svg: <Icons.SunIcon />,
  },
  {
    filename: "Icon/outline/moon",
    name: "moon",
    type: "Generic",
    svg: <Icons.MoonIcon />,
  },
  {
    filename: "Icon/outline/home",
    name: "home",
    type: "Generic",
    svg: <Icons.HomeIcon />,
  },
  {
    filename: "Icon/outline/search",
    name: "search",
    type: "Generic",
    svg: <Icons.SearchIcon />,
  },
  {
    filename: "Icon/outline/bell",
    name: "bell",
    type: "Generic",
    svg: <Icons.BellIcon />,
  },
  {
    filename: "Icon/outline/user",
    name: "user",
    type: "Generic",
    svg: <Icons.UserIcon />,
  },
  {
    filename: "Icon/outline/user-group",
    name: "user-group",
    type: "Generic",
    svg: <Icons.UserGroupIcon />,
  },
  {
    filename: "Icon/outline/edit",
    name: "edit",
    type: "Generic",
    svg: <Icons.EditIcon />,
  },
  {
    filename: "Icon/outline/trash",
    name: "trash",
    type: "Generic",
    svg: <Icons.TrashIcon />,
  },
  {
    filename: "Icon/outline/plus",
    name: "plus",
    type: "Generic",
    svg: <Icons.PlusIcon />,
  },
  {
    filename: "Icon/outline/plus-circle",
    name: "plus-circle",
    type: "Generic",
    svg: <Icons.PlusCircleIcon />,
  },
  {
    filename: "Icon/outline/zoom-in",
    name: "zoom-in",
    type: "Generic",
    svg: <Icons.ZoomInIcon />,
  },
  {
    filename: "Icon/outline/minus",
    name: "minus",
    type: "Generic",
    svg: <Icons.MinusIcon />,
  },
  {
    filename: "Icon/outline/minus-circle",
    name: "minus-circle",
    type: "Generic",
    svg: <Icons.MinusCircleIcon />,
  },
  {
    filename: "Icon/outline/zoom-out",
    name: "zoom-out",
    type: "Generic",
    svg: <Icons.ZoomOutIcon />,
  },
  {
    filename: "Icon/outline/table",
    name: "table",
    type: "Generic",
    svg: <Icons.TableIcon />,
  },
  {
    filename: "Icon/outline/grid",
    name: "grid",
    type: "Generic",
    svg: <Icons.GridIcon />,
  },
  {
    filename: "Icon/outline/list",
    name: "list",
    type: "Generic",
    svg: <Icons.ListIcon />,
  },
  {
    filename: "Icon/outline/upload",
    name: "upload",
    type: "Generic",
    svg: <Icons.UploadIcon />,
  },
  {
    filename: "Icon/outline/download",
    name: "download",
    type: "Generic",
    svg: <Icons.DownloadIcon />,
  },
  {
    filename: "Icon/outline/check",
    name: "check",
    type: "Generic",
    svg: <Icons.CheckIcon />,
  },
  {
    filename: "Icon/outline/check-circle",
    name: "check-circle",
    type: "Generic",
    svg: <Icons.CheckCircleIcon />,
  },
  {
    filename: "Icon/outline/cross",
    name: "cross",
    type: "Generic",
    svg: <Icons.CrossIcon />,
  },
  {
    filename: "Icon/outline/cross-circle",
    name: "cross-circle",
    type: "Generic",
    svg: <Icons.CrossCircleIcon />,
  },
  {
    filename: "Icon/outline/gov",
    name: "gov",
    type: "Generic",
    svg: <Icons.GovIcon />,
  },
  {
    filename: "Icon/outline/gov-my",
    name: "gov-my",
    type: "Generic",
    svg: <Icons.GovMyIcon />,
  },
  {
    filename: "Icon/outline/lock",
    name: "lock",
    type: "Generic",
    svg: <Icons.LockIcon />,
  },
  {
    filename: "Icon/outline/lock-2",
    name: "lock-2",
    type: "Generic",
    svg: <Icons.Lock2Icon />,
  },
  {
    filename: "Icon/outline/expand",
    name: "expand",
    type: "Generic",
    svg: <Icons.ExpandIcon />,
  },
  {
    filename: "Icon/outline/flag",
    name: "flag",
    type: "Generic",
    svg: <Icons.FlagIcon />,
  },
  {
    filename: "Icon/outline/thumbs-up",
    name: "thumbs-up",
    type: "Generic",
    svg: <Icons.ThumbsUpIcon />,
  },
  {
    filename: "Icon/outline/thumbs-down",
    name: "thumbs-down",
    type: "Generic",
    svg: <Icons.ThumbsDownIcon />,
  },
  {
    filename: "Icon/outline/cursor",
    name: "cursor",
    type: "Generic",
    svg: <Icons.CursorIcon />,
  },
  {
    filename: "Icon/outline/accessible",
    name: "accessible",
    type: "Generic",
    svg: <Icons.AccessibleIcon />,
  },
  {
    filename: "Icon/outline/heart",
    name: "heart",
    type: "Generic",
    svg: <Icons.HeartIcon />,
  },
  {
    filename: "Icon/outline/component",
    name: "component",
    type: "Generic",
    svg: <Icons.ComponentIcon />,
  },
  {
    filename: "Icon/outline/copy",
    name: "copy",
    type: "Generic",
    svg: <Icons.CopyIcon />,
  },
  {
    filename: "Icon/outline/duplicate",
    name: "duplicate",
    type: "Generic",
    svg: <Icons.DuplicateIcon />,
  },
  {
    filename: "Icon/outline/link",
    name: "link",
    type: "Generic",
    svg: <Icons.LinkIcon />,
  },
  {
    filename: "Icon/outline/eye-show",
    name: "eye-show",
    type: "Generic",
    svg: <Icons.EyeShowIcon />,
  },
  {
    filename: "Icon/outline/eye-hide",
    name: "eye-hide",
    type: "Generic",
    svg: <Icons.EyeHideIcon />,
  },
  {
    filename: "Icon/outline/options",
    name: "options",
    type: "Generic",
    svg: <Icons.OptionsIcon />,
  },
  {
    filename: "Icon/outline/options-vertical",
    name: "options-vertical",
    type: "Generic",
    svg: <Icons.OptionsVerticalIcon />,
  },
  {
    filename: "Icon/outline/calendar",
    name: "calendar",
    type: "Generic",
    svg: <Icons.CalendarIcon />,
  },
  {
    filename: "Icon/outline/clock",
    name: "clock",
    type: "Generic",
    svg: <Icons.ClockIcon />,
  },
  {
    filename: "Icon/outline/filter",
    name: "filter",
    type: "Generic",
    svg: <Icons.FilterIcon />,
  },
  {
    filename: "Icon/outline/filter-descending",
    name: "filter-descending",
    type: "Generic",
    svg: <Icons.FilterDescendingIcon />,
  },
  {
    filename: "Icon/outline/filter-ascending",
    name: "filter-ascending",
    type: "Generic",
    svg: <Icons.FilterAscendingIcon />,
  },
  {
    filename: "Icon/outline/map",
    name: "map",
    type: "Generic",
    svg: <Icons.MapIcon />,
  },
  {
    filename: "Icon/outline/direction",
    name: "direction",
    type: "Generic",
    svg: <Icons.DirectionIcon />,
  },
  {
    filename: "Icon/outline/pin",
    name: "pin",
    type: "Generic",
    svg: <Icons.PinIcon />,
  },
  {
    filename: "Icon/outline/warning",
    name: "warning",
    type: "Generic",
    svg: <Icons.WarningIcon />,
  },
  {
    filename: "Icon/outline/warning-diamond",
    name: "warning-diamond",
    type: "Generic",
    svg: <Icons.WarningDiamondIcon />,
  },
  {
    filename: "Icon/outline/warning-circle",
    name: "warning-circle",
    type: "Generic",
    svg: <Icons.WarningCircleIcon />,
  },
  {
    filename: "Icon/outline/info",
    name: "info",
    type: "Generic",
    svg: <Icons.InfoIcon />,
  },
  {
    filename: "Icon/outline/question-circle",
    name: "question-circle",
    type: "Generic",
    svg: <Icons.QuestionCircleIcon />,
  },

  {
    filename: "Icon/outline/printer",
    name: "printer",
    type: "Generic",
    svg: <Icons.PrinterIcon />,
  },
  {
    filename: "Icon/outline/book",
    name: "book",
    type: "Generic",
    svg: <Icons.BookIcon />,
  },
  {
    filename: "Icon/outline/globe",
    name: "globe",
    type: "Generic",
    svg: <Icons.GlobeIcon />,
  },
  {
    filename: "Icon/outline/money",
    name: "money",
    type: "Generic",
    svg: <Icons.MoneyIcon />,
  },
  {
    filename: "Icon/outline/qr-code",
    name: "qr-code",
    type: "Generic",
    svg: <Icons.QrCodeIcon />,
  },
  {
    filename: "Icon/outline/share",
    name: "share",
    type: "Generic",
    svg: <Icons.ShareIcon />,
  },
  {
    filename: "Icon/outline/folder",
    name: "folder",
    type: "Generic",
    svg: <Icons.FolderIcon />,
  },
  {
    filename: "Icon/outline/folder-plus",
    name: "folder-plus",
    type: "Generic",
    svg: <Icons.FolderPlusIcon />,
  },
  {
    filename: "Icon/outline/folder-minus",
    name: "folder-minus",
    type: "Generic",
    svg: <Icons.FolderMinusIcon />,
  },
  {
    filename: "Icon/outline/document-filled",
    name: "document-filled",
    type: "Generic",
    svg: <Icons.DocumentFilledIcon />,
  },
  {
    filename: "Icon/outline/document",
    name: "document",
    type: "Generic",
    svg: <Icons.DocumentIcon />,
  },
  {
    filename: "Icon/outline/document-add",
    name: "document-add",
    type: "Generic",
    svg: <Icons.DocumentAddIcon />,
  },
  {
    filename: "Icon/outline/document-minus",
    name: "document-minus",
    type: "Generic",
    svg: <Icons.DocumentMinusIcon />,
  },
  {
    filename: "Icon/outline/excel-file",
    name: "excel-file",
    type: "Generic",
    svg: <Icons.ExcelFileIcon />,
  },
  {
    filename: "Icon/outline/pdf-file",
    name: "pdf-file",
    type: "Generic",
    svg: <Icons.PdfFileIcon />,
  },
  {
    filename: "Icon/outline/doc-file",
    name: "doc-file",
    type: "Generic",
    svg: <Icons.DocFileIcon />,
  },
  {
    filename: "Icon/outline/attachment",
    name: "attachment",
    type: "Generic",
    svg: <Icons.AttachmentIcon />,
  },
  {
    filename: "Icon/outline/play",
    name: "play",
    type: "Generic",
    svg: <Icons.PlayIcon />,
  },
  {
    filename: "Icon/outline/pause",
    name: "pause",
    type: "Generic",
    svg: <Icons.PauseIcon />,
  },
  {
    filename: "Icon/outline/email",
    name: "email",
    type: "Generic",
    svg: <Icons.EmailIcon />,
  },
  {
    filename: "Icon/outline/phone",
    name: "phone",
    type: "Generic",
    svg: <Icons.PhoneIcon />,
  },
  {
    filename: "Icon/outline/mobile",
    name: "mobile",
    type: "Generic",
    svg: <Icons.MobileIcon />,
  },
  {
    filename: "Icon/outline/tablet",
    name: "tablet",
    type: "Generic",
    svg: <Icons.TabletIcon />,
  },
  {
    filename: "Icon/outline/desktop",
    name: "desktop",
    type: "Generic",
    svg: <Icons.DesktopIcon />,
  },
  {
    filename: "Icon/outline/bolt",
    name: "bolt",
    type: "Generic",
    svg: <Icons.BoltIcon />,
  },
  {
    filename: "Icon/outline/setting",
    name: "setting",
    type: "Generic",
    svg: <Icons.SettingIcon />,
  },
  {
    filename: "Icon/outline/chat-bubble",
    name: "chat-bubble",
    type: "Generic",
    svg: <Icons.ChatBubbleIcon />,
  },
  {
    filename: "Icon/outline/chevron-right",
    name: "chevron-right",
    type: "Generic",
    svg: <Icons.ChevronRightIcon />,
  },
  {
    filename: "Icon/outline/chevron-left",
    name: "chevron-left",
    type: "Generic",
    svg: <Icons.ChevronLeftIcon />,
  },
  {
    filename: "Icon/outline/chevron-down",
    name: "chevron-down",
    type: "Generic",
    svg: <Icons.ChevronDownIcon />,
  },
  {
    filename: "Icon/outline/chevron-up",
    name: "chevron-up",
    type: "Generic",
    svg: <Icons.ChevronUpIcon />,
  },
  {
    filename: "Icon/outline/column-expand",
    name: "column-expand",
    type: "Generic",
    svg: <Icons.ColumnExpandIcon />,
  },
  {
    filename: "Icon/outline/column-collapse",
    name: "column-collapse",
    type: "Generic",
    svg: <Icons.ColumnCollapseIcon />,
  },
  {
    filename: "Icon/outline/arrow-up",
    name: "arrow-up",
    type: "Generic",
    svg: <Icons.ArrowUpIcon />,
  },
  {
    filename: "Icon/outline/arrow-down",
    name: "arrow-down",
    type: "Generic",
    svg: <Icons.ArrowDownIcon />,
  },
  {
    filename: "Icon/outline/arrow-incoming",
    name: "arrow-incoming",
    type: "Generic",
    svg: <Icons.ArrowIncomingIcon />,
  },
  {
    filename: "Icon/outline/arrow-outgoing",
    name: "arrow-outgoing",
    type: "Generic",
    svg: <Icons.ArrowOutgoingIcon />,
  },
  {
    filename: "Icon/outline/arrow-back",
    name: "arrow-back",
    type: "Generic",
    svg: <Icons.ArrowBackIcon />,
  },
  {
    filename: "Icon/outline/arrow-forward",
    name: "arrow-forward",
    type: "Generic",
    svg: <Icons.ArrowForwardIcon />,
  },
  {
    filename: "Icon/outline/arrow-forward-close",
    name: "arrow-forward-close",
    type: "Generic",
    svg: <Icons.ArrowForwardCloseIcon />,
  },
  {
    filename: "Icon/outline/arrow-back-close",
    name: "arrow-back-close",
    type: "Generic",
    svg: <Icons.ArrowBackCloseIcon />,
  },
  {
    filename: "Icon/outline/undo",
    name: "undo",
    type: "Generic",
    svg: <Icons.UndoIcon />,
  },
  {
    filename: "Icon/outline/redo",
    name: "redo",
    type: "Generic",
    svg: <Icons.RedoIcon />,
  },
  {
    filename: "Icon/outline/logout",
    name: "logout",
    type: "Generic",
    svg: <Icons.LogoutIcon />,
  },
  {
    filename: "Icon/outline/drop-arrow-down",
    name: "drop-arrow-down",
    type: "Generic",
    svg: <Icons.DropArrowDownIcon />,
  },
  {
    filename: "Icon/outline/checkmark-shield",
    name: "checkmark-shield",
    type: "Generic",
    svg: <Icons.CheckmarkShieldIcon />,
  },
  {
    filename: "Icon/outline/checkmark-14-point-star",
    name: "checkmark-14-point-star",
    type: "Generic",
    svg: <Icons.Checkmark14PointStarIcon />,
  },
  {
    filename: "Icon/outline/trophy",
    name: "trophy",
    type: "Generic",
    svg: <Icons.TrophyIcon />,
  },
  {
    filename: "Icon/outline/star",
    name: "star",
    type: "Generic",
    svg: <Icons.StarIcon />,
  },
  {
    filename: "Icon/outline/swap",
    name: "swap",
    type: "Generic",
    svg: <Icons.SwapIcon />,
  },
  {
    filename: "Icon/outline/reload",
    name: "reload",
    type: "Generic",
    svg: <Icons.ReloadIcon />,
  },
  {
    filename: "Icon/outline/megaphone",
    name: "megaphone",
    type: "Generic",
    svg: <Icons.MegaphoneIcon />,
  },
  {
    filename: "Icon/outline/section",
    name: "section",
    type: "Generic",
    svg: <Icons.SectionIcon />,
  },
  {
    filename: "Icon/outline/text",
    name: "text",
    type: "Generic",
    svg: <Icons.TextIcon />,
  },
  {
    filename: "Icon/outline/button",
    name: "button",
    type: "Generic",
    svg: <Icons.ButtonIcon />,
  },
  {
    filename: "Icon/outline/gallery",
    name: "gallery",
    type: "Generic",
    svg: <Icons.GalleryIcon />,
  },
  {
    filename: "Icon/outline/image-slider",
    name: "image-slider",
    type: "Generic",
    svg: <Icons.ImageSliderIcon />,
  },
  {
    filename: "Icon/outline/video",
    name: "video",
    type: "Generic",
    svg: <Icons.VideoIcon />,
  },
  {
    filename: "Icon/outline/forms",
    name: "forms",
    type: "Generic",
    svg: <Icons.FormsIcon />,
  },
  {
    filename: "Icon/outline/forms-field",
    name: "forms-field",
    type: "Generic",
    svg: <Icons.FormsFieldIcon />,
  },
  {
    filename: "Icon/outline/database",
    name: "database",
    type: "Generic",
    svg: <Icons.DatabaseIcon />,
  },
  {
    filename: "Icon/outline/org-chart",
    name: "org-chart",
    type: "Generic",
    svg: <Icons.OrgChartIcon />,
  },
  ////////////////////////

  // Icon Filled : 9 Icons
  ////////////////////////
  {
    filename: "Icon/fill/chevron-down",
    type: "Generic: Filled",
    svg: <Icons.ChevronDownFillIcon />,
  },
  {
    filename: "Icon/fill/chevron-right",
    type: "Generic: Filled",
    svg: <Icons.ChevronRightFillIcon />,
  },
  {
    filename: "Icon/fill/chevron-left",
    type: "Generic: Filled",
    svg: <Icons.ChevronLeftFillIcon />,
  },
  {
    filename: "Icon/fill/chevron-up",
    type: "Generic: Filled",
    svg: <Icons.ChevronUpFillIcon />,
  },
  {
    filename: "Icon/fill/warning",
    type: "Generic: Filled",
    svg: <Icons.WarningFillIcon />,
  },
  {
    filename: "Icon/fill/check-circle",
    type: "Generic: Filled",
    svg: <Icons.CheckCircleFillIcon />,
  },
  {
    filename: "Icon/fill/lock",
    type: "Generic: Filled",
    svg: <Icons.LockFillIcon />,
  },
  {
    filename: "Icon/fill/star",
    type: "Generic: Filled",
    svg: <Icons.StarFillIcon />,
  },
  {
    filename: "Icon/fill/cross",
    type: "Generic: Filled",
    svg: <Icons.CrossFillIcon />,
  },
  ////////////////////////

  // WYSIWYG Icon : 14 icons
  {
    filename: "Size",
    type: "WYSIWYG",
    svg: <Icons.SizeWYSIWYGIcon />,
  },
  {
    filename: "Bold",
    type: "WYSIWYG",
    svg: <Icons.BoldWYSIWYGIcon />,
  },
  {
    filename: "Italic",
    type: "WYSIWYG",
    svg: <Icons.ItalicWYSIWYGIcon />,
  },
  {
    filename: "Underlined",
    type: "WYSIWYG",
    svg: <Icons.UnderlinedWYSIWYGIcon />,
  },
  {
    filename: "Strikethrough",
    type: "WYSIWYG",
    svg: <Icons.StrikethroughWYSIWYGIcon />,
  },
  { filename: "Link", type: "WYSIWYG", svg: <Icons.LinkIcon /> },
  {
    filename: "Unlink",
    type: "WYSIWYG",
    svg: <Icons.UnlinkWYSIWYGIcon />,
  },
  {
    filename: "Numbered-List",
    type: "WYSIWYG",
    svg: <Icons.NumberedListWYSIWYGIcon />,
  },
  {
    filename: "Bulleted-List",
    type: "WYSIWYG",
    svg: <Icons.BulletedListWYSIWYGIcon />,
  },
  {
    filename: "Align-Left",
    type: "WYSIWYG",
    svg: <Icons.AlignLeftWYSIWYGIcon />,
  },
  {
    filename: "Align-Center",
    type: "WYSIWYG",
    svg: <Icons.AlignCenterWYSIWYGIcon />,
  },
  {
    filename: "Align-Right",
    type: "WYSIWYG",
    svg: <Icons.AlignRightWYSIWYGIcon />,
  },
  {
    filename: "Align-Justify",
    type: "WYSIWYG",
    svg: <Icons.AlignJustifyWYSIWYGIcon />,
  },
  {
    filename: "Reset-Style",
    type: "WYSIWYG",
    svg: <Icons.ResetStyleWYSIWYGIcon />,
  },

  // Social Media Icon
  {
    filename: "RSS",
    type: "Social Media",
    svg: <Icons.RSSIcon />,
  },
  { filename: "Facebook", type: "Social Media", svg: <Icons.FacebookIcon /> },
  { filename: "X", type: "Social Media", svg: <Icons.XIcon /> },
  { filename: "LinkedIn", type: "Social Media", svg: <Icons.LinkedInIcon /> },
  { filename: "Instagram", type: "Social Media", svg: <Icons.InstagramIcon /> },
  { filename: "Youtube", type: "Social Media", svg: <Icons.YoutubeIcon /> },
  { filename: "Whatsapp", type: "Social Media", svg: <Icons.WhatsappIcon /> },
  { filename: "TikTok", type: "Social Media", svg: <Icons.TikTokIcon /> },
  { filename: "Figma", type: "Social Media", svg: <Icons.FigmaIcon /> },
  { filename: "Telegram", type: "Social Media", svg: <Icons.TelegramIcon /> },
  { filename: "GitHub", type: "Social Media", svg: <Icons.GitHubIcon /> },
  { filename: "Google", type: "Social Media", svg: <Icons.GoogleIcon /> },

  // Media Icon
  {
    filename: "Icon/file/PPTX",
    type: "Media",
    svg: <Icons.PPTXMediaIcon />,
  },
  {
    filename: "Icon/file/XLSX",
    type: "Media",
    svg: <Icons.XLSXMediaIcon />,
  },
  {
    filename: "Icon/file/DOCX",
    type: "Media",
    svg: <Icons.DOCXMediaIcon />,
  },
  {
    filename: "Icon/file/PDF",
    type: "Media",
    svg: <Icons.PDFMediaIcon />,
  },

  // LEGACY Generic Icons
  {
    filename: "agency-icon/jata-negara",
    type: "Legacy: Generic",
    svg: <Icons.LegacyJataNegaraIcon />,
  },
  {
    filename: "agency-icon/dosm",
    type: "Legacy: Generic",
    svg: <Icons.LegacyDosmIcon />,
  },
  {
    filename: "agency-icon/identity-jpn",
    type: "Legacy: Generic",
    svg: <Icons.LegacyIdentityJpnIcon />,
  },
  {
    filename: "agency-icon/car-jpj",
    type: "Legacy: Generic",
    svg: <Icons.LegacyCarJpjIcon />,
  },
  {
    filename: "agency-icon/book-moe",
    type: "Legacy: Generic",
    svg: <Icons.LegacyBookMoeIcon />,
  },
  {
    filename: "agency-icon/internet-mcmc",
    type: "Legacy: Generic",
    svg: <Icons.LegacyInternetMcmcIcon />,
  },
  {
    filename: "agency-icon/money-kwap",
    type: "Legacy: Generic",
    svg: <Icons.LegacyMoneyKwapIcon />,
  },
  {
    filename: "agency-icon/helmet-jpa",
    type: "Legacy: Generic",
    svg: <Icons.LegacyHelmetJpaIcon />,
  },
  {
    filename: "agency-icon/train-mot",
    type: "Legacy: Generic",
    svg: <Icons.LegacyTrainMotIcon />,
  },
  {
    filename: "agency-icon/unhcr",
    type: "Legacy: Generic",
    svg: <Icons.LegacyUnhcrIcon />,
  },
  {
    filename: "agency-icon/ribbon-ntrc",
    type: "Legacy: Generic",
    svg: <Icons.LegacyRibbonNtrcIcon />,
  },
  {
    filename: "agency-icon/weather-met",
    type: "Legacy: Generic",
    svg: <Icons.LegacyWeatherMetIcon />,
  },
  {
    filename: "agency-icon/flood-jps",
    type: "Legacy: Generic",
    svg: <Icons.LegacyFloodJpsIcon />,
  },
  {
    filename: "agency-icon/jakoa",
    type: "Legacy: Generic",
    svg: <Icons.LegacyJakoaIcon />,
  },
  {
    filename: "agency-icon/blood-pdn",
    type: "Legacy: Generic",
    svg: <Icons.LegacyBloodPdnIcon />,
  },
  {
    filename: "agency-icon/ballot-spr",
    type: "Legacy: Generic",
    svg: <Icons.LegacyBallotSprIcon />,
  },
  {
    filename: "agency-icon/fire-bomba",
    type: "Legacy: Generic",
    svg: <Icons.LegacyFireBombaIcon />,
  },
  {
    filename: "agency-icon/ambulance-mers",
    type: "Legacy: Generic",
    svg: <Icons.LegacyAmbulanceMersIcon />,
  },
  {
    filename: "agency-icon/hospital-moh",
    type: "Legacy: Generic",
    svg: <Icons.LegacyHospitalMohIcon />,
  },
  {
    filename: "agency-icon/phcorp",
    type: "Legacy: Generic",
    svg: <Icons.LegacyPhcorpIcon />,
  },
  {
    filename: "agency-icon/passport-imigresen",
    type: "Legacy: Generic",
    svg: <Icons.LegacyPassportImigresenIcon />,
  },
  {
    filename: "agency-icon/bnm",
    type: "Legacy: Generic",
    svg: <Icons.LegacyBnmIcon />,
  },
  {
    filename: "agency-icon/money-epf",
    type: "Legacy: Generic",
    svg: <Icons.LegacyMoneyEpfIcon />,
  },
  {
    filename: "agency-icon/money-lhdn",
    type: "Legacy: Generic",
    svg: <Icons.LegacyMoneyLhdnIcon />,
  },
  {
    filename: "agency-icon/mampu",
    type: "Legacy: Generic",
    svg: <Icons.LegacyMampuIcon />,
  },
  {
    filename: "agency-icon/socso-perkeso",
    type: "Legacy: Generic",
    svg: <Icons.LegacySocsoPerkesoIcon />,
  },
  {
    filename: "agency-icon/light-bulb-ipr-epu",
    type: "Legacy: Generic",
    svg: <Icons.LegacyLightBulbIprEpuIcon />,
  },
  {
    filename: "agency-icon/police-pdrm",
    type: "Legacy: Generic",
    svg: <Icons.LegacyPolicePdrmIcon />,
  },
  {
    filename: "agency-icon/helping-hand-icu-jpm",
    type: "Legacy: Generic",
    svg: <Icons.LegacyHelpingHandIcuJpmIcon />,
  },
  {
    filename: "agency-icon/document-mof",
    type: "Legacy: Generic",
    svg: <Icons.LegacyDocumentMofIcon />,
  },

  // Without Round Shape or Borderless
  {
    filename: "agency-icons/mini/phcorp",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniPhcorpIcon />,
  },
  {
    filename: "agency-icons/mini/mampu",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniMampuIcon />,
  },
  {
    filename: "agency-icons/mini/ribbon-ntrc",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniRibbonNtrcIcon />,
  },
  {
    filename: "agency-icons/mini/bnm",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniBnmIcon />,
  },
  {
    filename: "agency-icons/mini/dosm",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniDosmIcon />,
  },
  {
    filename: "agency-icons/mini/helmet-jpa",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniHelmetJpaIcon />,
  },
  {
    filename: "agency-icons/mini/document-mof",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniDocumentMofIcon />,
  },
  {
    filename: "agency-icons/mini/train-mot",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniTrainMotIcon />,
  },
  {
    filename: "agency-icons/mini/ambulance-mers",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniAmbulanceMersIcon />,
  },
  {
    filename: "agency-icons/mini/hospital-moh",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniHospitalMohIcon />,
  },
  {
    filename: "agency-icons/mini/police-pdrm",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniPolicePdrmIcon />,
  },
  {
    filename: "agency-icons/mini/weather-climate",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniWeatherClimateIcon />,
  },
  {
    filename: "agency-icons/mini/fire-bomba",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniFireBombaIcon />,
  },
  {
    filename: "agency-icons/mini/flood-warning",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniFloodWarningIcon />,
  },
  {
    filename: "agency-icons/mini/light-bulb-ipr-epu",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniLightBulbIprEpuIcon />,
  },
  {
    filename: "agency-icons/mini/helping-hands-icu-jpm",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniHelpingHandsIcuJpmIcon />,
  },
  {
    filename: "agency-icons/mini/money-kwap",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniMoneyKwapIcon />,
  },
  {
    filename: "agency-icons/mini/ballot-spr",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniBallotSprIcon />,
  },
  {
    filename: "agency-icons/mini/money-epf",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniMoneyEpfIcon />,
  },
  {
    filename: "agency-icons/mini/book-moe",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniBookMoeIcon />,
  },
  {
    filename: "agency-icons/mini/passport-imigresen",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniPassportImigresenIcon />,
  },
  {
    filename: "agency-icons/mini/internet-mcmc",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniInternetMcmcIcon />,
  },
  {
    filename: "agency-icons/mini/blood-pdn",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniBloodPdnIcon />,
  },
  {
    filename: "agency-icons/mini/car-jpj",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniCarJpjIcon />,
  },
  {
    filename: "agency-icons/mini/identity-jpn",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniIdentityJpnIcon />,
  },
  {
    filename: "agency-icons/mini/socsco",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniSocsoIcon />,
  },
  {
    filename: "agency-icons/mini/money-lhdn",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniMoneyLhdnIcon />,
  },
  {
    filename: "agency-icons/mini/unhcr",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniUnhcrIcon />,
  },
  {
    filename: "agency-icons/mini/jakoa",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniJakoaIcon />,
  },
  {
    filename: "agency-icons/mini/website",
    type: "Legacy: Borderless",
    svg: <Icons.LegacyMiniWebsiteIcon />,
  },
];
