import * as Icons from "@govtechmy/myds-react/icon";

export type IconData = {
  filename: string;
  name?: string;
  type: string;
  svg: React.ReactNode;
};

export type IconDataList = IconData[];

export const iconDataList: IconData[] = [
  //Generic Icons : 120 icons
  //Remove 1 Icon - Placeholder

  {
    filename: "Icon/outline/malaysia-flag",
    name: "malaysia-flag",
    type: "Media",
    svg: <Icons.MalaysiaFlagIcon />,
  },
  {
    filename: "agency-icon/jata-negara",
    name: "jata-negara",
    type: "Media",
    svg: <Icons.JataNegaraIcon />,
  },
  {
    filename: "Icon/outline/hamburger-menu",
    name: "hamburger-menu",
    type: "Generic",
    svg: <Icons.HamburgerMenuIcon />,
  },
  {
    filename: "Icon/outline/sun",
    name: "sun",
    type: "Generic",
    svg: <Icons.SunIcon />,
  },
  {
    filename: "Icon/outline/moon",
    name: "moon",
    type: "Generic",
    svg: <Icons.MoonIcon />,
  },
  {
    filename: "Icon/outline/home",
    name: "home",
    type: "Generic",
    svg: <Icons.HomeIcon />,
  },
  {
    filename: "Icon/outline/search",
    name: "search",
    type: "Generic",
    svg: <Icons.SearchIcon />,
  },
  {
    filename: "Icon/outline/bell",
    name: "bell",
    type: "Generic",
    svg: <Icons.BellIcon />,
  },
  {
    filename: "Icon/outline/user",
    name: "user",
    type: "Generic",
    svg: <Icons.UserIcon />,
  },
  {
    filename: "Icon/outline/user-group",
    name: "user-group",
    type: "Generic",
    svg: <Icons.UserGroupIcon />,
  },
  {
    filename: "Icon/outline/edit",
    name: "edit",
    type: "Generic",
    svg: <Icons.EditIcon />,
  },
  {
    filename: "Icon/outline/trash",
    name: "trash",
    type: "Generic",
    svg: <Icons.TrashIcon />,
  },
  {
    filename: "Icon/outline/plus",
    name: "plus",
    type: "Generic",
    svg: <Icons.PlusIcon />,
  },
  {
    filename: "Icon/outline/plus-circle",
    name: "plus-circle",
    type: "Generic",
    svg: <Icons.PlusCircleIcon />,
  },
  {
    filename: "Icon/outline/zoom-in",
    name: "zoom-in",
    type: "Generic",
    svg: <Icons.ZoomInIcon />,
  },
  {
    filename: "Icon/outline/minus",
    name: "minus",
    type: "Generic",
    svg: <Icons.MinusIcon />,
  },
  {
    filename: "Icon/outline/minus-circle",
    name: "minus-circle",
    type: "Generic",
    svg: <Icons.MinusCircleIcon />,
  },
  {
    filename: "Icon/outline/zoom-out",
    name: "zoom-out",
    type: "Generic",
    svg: <Icons.ZoomOutIcon />,
  },
  {
    filename: "Icon/outline/table",
    name: "table",
    type: "Generic",
    svg: <Icons.TableIcon />,
  },
  {
    filename: "Icon/outline/grid",
    name: "grid",
    type: "Generic",
    svg: <Icons.GridIcon />,
  },
  {
    filename: "Icon/outline/list",
    name: "list",
    type: "Generic",
    svg: <Icons.ListIcon />,
  },
  {
    filename: "Icon/outline/upload",
    name: "upload",
    type: "Generic",
    svg: <Icons.UploadIcon />,
  },
  {
    filename: "Icon/outline/download",
    name: "download",
    type: "Generic",
    svg: <Icons.DownloadIcon />,
  },
  {
    filename: "Icon/outline/check",
    name: "check",
    type: "Generic",
    svg: <Icons.CheckIcon />,
  },
  {
    filename: "Icon/outline/check-circle",
    name: "check-circle",
    type: "Generic",
    svg: <Icons.CheckCircleIcon />,
  },
  {
    filename: "Icon/outline/cross",
    name: "cross",
    type: "Generic",
    svg: <Icons.CrossIcon />,
  },
  {
    filename: "Icon/outline/cross-circle",
    name: "cross-circle",
    type: "Generic",
    svg: <Icons.CrossCircleIcon />,
  },
  {
    filename: "Icon/outline/govt-office",
    name: "govt-office",
    type: "Generic",
    svg: <Icons.GovtOfficeIcon />,
  },
  {
    filename: "Icon/outline/putrajaya",
    name: "putrajaya",
    type: "Generic",
    svg: <Icons.PutrajayaIcon />,
  },
  {
    filename: "Icon/outline/lock",
    name: "lock",
    type: "Generic",
    svg: <Icons.LockIcon />,
  },
  {
    filename: "Icon/outline/lock-2",
    name: "lock-2",
    type: "Generic",
    svg: <Icons.Lock2Icon />,
  },
  {
    filename: "Icon/outline/expand",
    name: "expand",
    type: "Generic",
    svg: <Icons.ExpandIcon />,
  },
  {
    filename: "Icon/outline/flag",
    name: "flag",
    type: "Generic",
    svg: <Icons.FlagIcon />,
  },
  {
    filename: "Icon/outline/thumbs-up",
    name: "thumbs-up",
    type: "Generic",
    svg: <Icons.ThumbsUpIcon />,
  },
  {
    filename: "Icon/outline/thumbs-down",
    name: "thumbs-down",
    type: "Generic",
    svg: <Icons.ThumbsDownIcon />,
  },
  {
    filename: "Icon/outline/cursor",
    name: "cursor",
    type: "Generic",
    svg: <Icons.CursorIcon />,
  },
  {
    filename: "Icon/outline/accessible",
    name: "accessible",
    type: "Generic",
    svg: <Icons.AccessibleIcon />,
  },
  {
    filename: "Icon/outline/heart",
    name: "heart",
    type: "Generic",
    svg: <Icons.HeartIcon />,
  },
  {
    filename: "Icon/outline/component",
    name: "component",
    type: "Generic",
    svg: <Icons.ComponentIcon />,
  },
  {
    filename: "Icon/outline/copy",
    name: "copy",
    type: "Generic",
    svg: <Icons.CopyIcon />,
  },
  {
    filename: "Icon/outline/duplicate",
    name: "duplicate",
    type: "Generic",
    svg: <Icons.DuplicateIcon />,
  },
  {
    filename: "Icon/outline/link",
    name: "link",
    type: "Generic",
    svg: <Icons.LinkIcon />,
  },
  {
    filename: "Icon/outline/link-diagonal",
    name: "link-diagonal",
    type: "Generic",
    svg: <Icons.LinkDiagonalIcon />,
  },
  {
    filename: "Icon/outline/eye-show",
    name: "eye-show",
    type: "Generic",
    svg: <Icons.EyeShowIcon />,
  },
  {
    filename: "Icon/outline/eye-hide",
    name: "eye-hide",
    type: "Generic",
    svg: <Icons.EyeHideIcon />,
  },
  {
    filename: "Icon/outline/ellipsis",
    name: "ellipsis",
    type: "Generic",
    svg: <Icons.EllipsisIcon />,
  },
  {
    filename: "Icon/outline/ellipsis-vertical",
    name: "ellipsis-vertical",
    type: "Generic",
    svg: <Icons.EllipsisVerticalIcon />,
  },
  {
    filename: "Icon/outline/calendar",
    name: "calendar",
    type: "Generic",
    svg: <Icons.CalendarIcon />,
  },
  {
    filename: "Icon/outline/clock",
    name: "clock",
    type: "Generic",
    svg: <Icons.ClockIcon />,
  },
  {
    filename: "Icon/outline/filter",
    name: "filter",
    type: "Generic",
    svg: <Icons.FilterIcon />,
  },
  {
    filename: "Icon/outline/filter-desc",
    name: "filter-desc",
    type: "Generic",
    svg: <Icons.FilterDescIcon />,
  },
  {
    filename: "Icon/outline/filter-asc",
    name: "filter-asc",
    type: "Generic",
    svg: <Icons.FilterAscIcon />,
  },
  {
    filename: "Icon/outline/map",
    name: "map",
    type: "Generic",
    svg: <Icons.MapIcon />,
  },
  {
    filename: "Icon/outline/direction",
    name: "direction",
    type: "Generic",
    svg: <Icons.DirectionIcon />,
  },
  {
    filename: "Icon/outline/pin",
    name: "pin",
    type: "Generic",
    svg: <Icons.PinIcon />,
  },
  {
    filename: "Icon/outline/warning",
    name: "warning",
    type: "Generic",
    svg: <Icons.WarningIcon />,
  },
  {
    filename: "Icon/outline/warning-diamond",
    name: "warning-diamond",
    type: "Generic",
    svg: <Icons.WarningDiamondIcon />,
  },
  {
    filename: "Icon/outline/warning-circle",
    name: "warning-circle",
    type: "Generic",
    svg: <Icons.WarningCircleIcon />,
  },
  {
    filename: "Icon/outline/info",
    name: "info",
    type: "Generic",
    svg: <Icons.InfoIcon />,
  },
  {
    filename: "Icon/outline/question-circle",
    name: "question-circle",
    type: "Generic",
    svg: <Icons.QuestionCircleIcon />,
  },

  {
    filename: "Icon/outline/printer",
    name: "printer",
    type: "Generic",
    svg: <Icons.PrinterIcon />,
  },
  {
    filename: "Icon/outline/book",
    name: "book",
    type: "Generic",
    svg: <Icons.BookIcon />,
  },
  {
    filename: "Icon/outline/globe",
    name: "globe",
    type: "Generic",
    svg: <Icons.GlobeIcon />,
  },
  {
    filename: "Icon/outline/money",
    name: "money",
    type: "Generic",
    svg: <Icons.MoneyIcon />,
  },
  {
    filename: "Icon/outline/qr-code",
    name: "qr-code",
    type: "Generic",
    svg: <Icons.QrCodeIcon />,
  },
  {
    filename: "Icon/outline/share",
    name: "share",
    type: "Generic",
    svg: <Icons.ShareIcon />,
  },
  {
    filename: "Icon/outline/folder",
    name: "folder",
    type: "Generic",
    svg: <Icons.FolderIcon />,
  },
  {
    filename: "Icon/outline/folder-plus",
    name: "folder-plus",
    type: "Generic",
    svg: <Icons.FolderPlusIcon />,
  },
  {
    filename: "Icon/outline/folder-minus",
    name: "folder-minus",
    type: "Generic",
    svg: <Icons.FolderMinusIcon />,
  },
  {
    filename: "Icon/outline/document-filled",
    name: "document-filled",
    type: "Generic",
    svg: <Icons.DocumentFilledIcon />,
  },
  {
    filename: "Icon/outline/document",
    name: "document",
    type: "Generic",
    svg: <Icons.DocumentIcon />,
  },
  {
    filename: "Icon/outline/document-add",
    name: "document-add",
    type: "Generic",
    svg: <Icons.DocumentAddIcon />,
  },
  {
    filename: "Icon/outline/document-minus",
    name: "document-minus",
    type: "Generic",
    svg: <Icons.DocumentMinusIcon />,
  },
  {
    filename: "Icon/outline/excel",
    name: "excel",
    type: "Generic",
    svg: <Icons.ExcelIcon />,
  },
  {
    filename: "Icon/outline/pdf",
    name: "pdf",
    type: "Generic",
    svg: <Icons.PdfIcon />,
  },
  {
    filename: "Icon/outline/word",
    name: "word",
    type: "Generic",
    svg: <Icons.WordIcon />,
  },
  {
    filename: "Icon/outline/attachment",
    name: "attachment",
    type: "Generic",
    svg: <Icons.AttachmentIcon />,
  },
  {
    filename: "Icon/outline/play",
    name: "play",
    type: "Generic",
    svg: <Icons.PlayIcon />,
  },
  {
    filename: "Icon/outline/pause",
    name: "pause",
    type: "Generic",
    svg: <Icons.PauseIcon />,
  },
  {
    filename: "Icon/outline/email",
    name: "email",
    type: "Generic",
    svg: <Icons.EmailIcon />,
  },
  {
    filename: "Icon/outline/phone",
    name: "phone",
    type: "Generic",
    svg: <Icons.PhoneIcon />,
  },
  {
    filename: "Icon/outline/mobile",
    name: "mobile",
    type: "Generic",
    svg: <Icons.MobileIcon />,
  },
  {
    filename: "Icon/outline/tablet",
    name: "tablet",
    type: "Generic",
    svg: <Icons.TabletIcon />,
  },
  {
    filename: "Icon/outline/desktop",
    name: "desktop",
    type: "Generic",
    svg: <Icons.DesktopIcon />,
  },
  {
    filename: "Icon/outline/bolt",
    name: "bolt",
    type: "Generic",
    svg: <Icons.BoltIcon />,
  },
  {
    filename: "Icon/outline/setting",
    name: "setting",
    type: "Generic",
    svg: <Icons.SettingIcon />,
  },
  {
    filename: "Icon/outline/chat-bubble",
    name: "chat-bubble",
    type: "Generic",
    svg: <Icons.ChatBubbleIcon />,
  },
  {
    filename: "Icon/outline/chevron-right",
    name: "chevron-right",
    type: "Generic",
    svg: <Icons.ChevronRightIcon />,
  },
  {
    filename: "Icon/outline/chevron-left",
    name: "chevron-left",
    type: "Generic",
    svg: <Icons.ChevronLeftIcon />,
  },
  {
    filename: "Icon/outline/chevron-down",
    name: "chevron-down",
    type: "Generic",
    svg: <Icons.ChevronDownIcon />,
  },
  {
    filename: "Icon/outline/chevron-up",
    name: "chevron-up",
    type: "Generic",
    svg: <Icons.ChevronUpIcon />,
  },
  {
    filename: "Icon/outline/column-expand",
    name: "column-expand",
    type: "Generic",
    svg: <Icons.ColumnExpandIcon />,
  },
  {
    filename: "Icon/outline/column-collapse",
    name: "column-collapse",
    type: "Generic",
    svg: <Icons.ColumnCollapseIcon />,
  },
  {
    filename: "Icon/outline/arrow-up",
    name: "arrow-up",
    type: "Generic",
    svg: <Icons.ArrowUpIcon />,
  },
  {
    filename: "Icon/outline/arrow-down",
    name: "arrow-down",
    type: "Generic",
    svg: <Icons.ArrowDownIcon />,
  },
  {
    filename: "Icon/outline/arrow-incoming",
    name: "arrow-incoming",
    type: "Generic",
    svg: <Icons.ArrowIncomingIcon />,
  },
  {
    filename: "Icon/outline/arrow-outgoing",
    name: "arrow-outgoing",
    type: "Generic",
    svg: <Icons.ArrowOutgoingIcon />,
  },
  {
    filename: "Icon/outline/arrow-back",
    name: "arrow-back",
    type: "Generic",
    svg: <Icons.ArrowBackIcon />,
  },
  {
    filename: "Icon/outline/arrow-forward",
    name: "arrow-forward",
    type: "Generic",
    svg: <Icons.ArrowForwardIcon />,
  },
  {
    filename: "Icon/outline/arrow-forward-close",
    name: "arrow-forward-close",
    type: "Generic",
    svg: <Icons.ArrowForwardCloseIcon />,
  },
  {
    filename: "Icon/outline/arrow-back-close",
    name: "arrow-back-close",
    type: "Generic",
    svg: <Icons.ArrowBackCloseIcon />,
  },
  {
    filename: "Icon/outline/undo",
    name: "undo",
    type: "Generic",
    svg: <Icons.UndoIcon />,
  },
  {
    filename: "Icon/outline/redo",
    name: "redo",
    type: "Generic",
    svg: <Icons.RedoIcon />,
  },
  {
    filename: "Icon/outline/logout",
    name: "logout",
    type: "Generic",
    svg: <Icons.LogoutIcon />,
  },
  {
    filename: "Icon/outline/drop-arrow-down",
    name: "drop-arrow-down",
    type: "Generic",
    svg: <Icons.DropArrowDownIcon />,
  },
  {
    filename: "Icon/outline/check-shield",
    name: "check-shield",
    type: "Generic",
    svg: <Icons.CheckShieldIcon />,
  },
  {
    filename: "Icon/outline/check-star",
    name: "check-star",
    type: "Generic",
    svg: <Icons.CheckStarIcon />,
  },
  {
    filename: "Icon/outline/trophy",
    name: "trophy",
    type: "Generic",
    svg: <Icons.TrophyIcon />,
  },
  {
    filename: "Icon/outline/star",
    name: "star",
    type: "Generic",
    svg: <Icons.StarIcon />,
  },
  {
    filename: "Icon/outline/swap",
    name: "swap",
    type: "Generic",
    svg: <Icons.SwapIcon />,
  },
  {
    filename: "Icon/outline/reload",
    name: "reload",
    type: "Generic",
    svg: <Icons.ReloadIcon />,
  },
  {
    filename: "Icon/outline/megaphone",
    name: "megaphone",
    type: "Generic",
    svg: <Icons.MegaphoneIcon />,
  },
  {
    filename: "Icon/outline/section",
    name: "section",
    type: "Generic",
    svg: <Icons.SectionIcon />,
  },
  {
    filename: "Icon/outline/text",
    name: "text",
    type: "Generic",
    svg: <Icons.TextIcon />,
  },
  {
    filename: "Icon/outline/button",
    name: "button",
    type: "Generic",
    svg: <Icons.ButtonIcon />,
  },
  {
    filename: "Icon/outline/gallery",
    name: "gallery",
    type: "Generic",
    svg: <Icons.GalleryIcon />,
  },
  {
    filename: "Icon/outline/carousel",
    name: "carousel",
    type: "Generic",
    svg: <Icons.CarouselIcon />,
  },
  {
    filename: "Icon/outline/video",
    name: "video",
    type: "Generic",
    svg: <Icons.VideoIcon />,
  },
  {
    filename: "Icon/outline/forms",
    name: "forms",
    type: "Generic",
    svg: <Icons.FormsIcon />,
  },
  {
    filename: "Icon/outline/input-field",
    name: "input-field",
    type: "Generic",
    svg: <Icons.InputFieldIcon />,
  },
  {
    filename: "Icon/outline/database",
    name: "database",
    type: "Generic",
    svg: <Icons.DatabaseIcon />,
  },
  {
    filename: "Icon/outline/org-chart",
    name: "org-chart",
    type: "Generic",
    svg: <Icons.OrgChartIcon />,
  },
  ////////////////////////

  // Icon Filled : 9 Icons
  ////////////////////////
  {
    filename: "Icon/fill/chevron-down-fill",
    name: "chevron-down-fill",
    type: "Generic: Filled",
    svg: <Icons.ChevronDownFillIcon />,
  },
  {
    filename: "Icon/fill/chevron-right-fill",
    name: "chevron-right-fill",
    type: "Generic: Filled",
    svg: <Icons.ChevronRightFillIcon />,
  },
  {
    filename: "Icon/fill/chevron-left-fill",
    name: "chevron-left-fill",
    type: "Generic: Filled",
    svg: <Icons.ChevronLeftFillIcon />,
  },
  {
    filename: "Icon/fill/chevron-up-fill",
    name: "chevron-up-fill",
    type: "Generic: Filled",
    svg: <Icons.ChevronUpFillIcon />,
  },
  {
    filename: "Icon/fill/warning-fill",
    name: "warning-fill",
    type: "Generic: Filled",
    svg: <Icons.WarningFillIcon />,
  },
  {
    filename: "Icon/fill/check-circle-fill",
    name: "check-circle-fill",
    type: "Generic: Filled",
    svg: <Icons.CheckCircleFillIcon />,
  },
  {
    filename: "Icon/fill/lock-fill",
    name: "lock-fill",
    type: "Generic: Filled",
    svg: <Icons.LockFillIcon />,
  },
  {
    filename: "Icon/fill/star-fill",
    name: "star-fill",
    type: "Generic: Filled",
    svg: <Icons.StarFillIcon />,
  },
  {
    filename: "Icon/fill/cross-fill",
    name: "cross-fill",
    type: "Generic: Filled",
    svg: <Icons.CrossFillIcon />,
  },

  ////////////////////////

  // WYSIWYG Icon : 14 icons
  {
    filename: "Font",
    name: "font",
    type: "WYSIWYG",
    svg: <Icons.FontIcon />,
  },
  {
    filename: "Bold",
    name: "bold",
    type: "WYSIWYG",
    svg: <Icons.BoldIcon />,
  },
  {
    filename: "Italic",
    name: "italic",
    type: "WYSIWYG",
    svg: <Icons.ItalicIcon />,
  },
  {
    filename: "Underline",
    name: "underline",
    type: "WYSIWYG",
    svg: <Icons.UnderlineIcon />,
  },
  {
    filename: "Strikethrough",
    name: "strikethrough",
    type: "WYSIWYG",
    svg: <Icons.StrikethroughIcon />,
  },
  {
    filename: "Link",
    name: "link",
    type: "WYSIWYG",
    svg: <Icons.LinkIcon />,
  },
  {
    filename: "Unlink",
    name: "unlink",
    type: "WYSIWYG",
    svg: <Icons.UnlinkIcon />,
  },
  {
    filename: "Numbered-List",
    name: "numbered-list",
    type: "WYSIWYG",
    svg: <Icons.NumberedListIcon />,
  },
  {
    filename: "Bulleted-List",
    name: "bulleted-list",
    type: "WYSIWYG",
    svg: <Icons.BulletedListIcon />,
  },
  {
    filename: "Align-Left",
    name: "align-left",
    type: "WYSIWYG",
    svg: <Icons.AlignLeftIcon />,
  },
  {
    filename: "Align-Center",
    name: "align-center",
    type: "WYSIWYG",
    svg: <Icons.AlignCenterIcon />,
  },
  {
    filename: "Align-Right",
    name: "align-right",
    type: "WYSIWYG",
    svg: <Icons.AlignRightIcon />,
  },
  {
    filename: "Align-Justify",
    name: "align-justify",
    type: "WYSIWYG",
    svg: <Icons.AlignJustifyIcon />,
  },
  {
    filename: "Reset-Style",
    name: "reset-style",
    type: "WYSIWYG",
    svg: <Icons.ResetStyleIcon />,
  },

  // Social Media Icon
  {
    filename: "RSS",
    name: "rss",
    type: "Social Media",
    svg: <Icons.RSSIcon />,
  },
  {
    filename: "Facebook",
    name: "facebook",
    type: "Social Media",
    svg: <Icons.FacebookIcon />,
  },
  {
    filename: "X",
    name: "x",
    type: "Social Media",
    svg: <Icons.TwitterXIcon />,
  },
  {
    filename: "LinkedIn",
    name: "linkedin",
    type: "Social Media",
    svg: <Icons.LinkedinIcon />,
  },
  {
    filename: "Instagram",
    name: "instagram",
    type: "Social Media",
    svg: <Icons.InstagramIcon />,
  },
  {
    filename: "Youtube",
    name: "youtube",
    type: "Social Media",
    svg: <Icons.YoutubeIcon />,
  },
  {
    filename: "Whatsapp",
    name: "whatsapp",
    type: "Social Media",
    svg: <Icons.WhatsappIcon />,
  },
  {
    filename: "TikTok",
    name: "tiktok",
    type: "Social Media",
    svg: <Icons.TiktokIcon />,
  },
  {
    filename: "Figma",
    name: "figma",
    type: "Social Media",
    svg: <Icons.FigmaIcon />,
  },
  {
    filename: "Telegram",
    name: "telegram",
    type: "Social Media",
    svg: <Icons.TelegramIcon />,
  },
  {
    filename: "GitHub",
    name: "github",
    type: "Social Media",
    svg: <Icons.GithubIcon />,
  },
  {
    filename: "Google",
    name: "google",
    type: "Social Media",
    svg: <Icons.GoogleIcon />,
  },

  // Media Icons
  {
    filename: "Icon/file/powerpoint-media",
    name: "powerpoint-media",
    type: "Media",
    svg: <Icons.PowerpointMediaIcon />,
  },
  {
    filename: "Icon/file/excel-media",
    name: "excel-media",
    type: "Media",
    svg: <Icons.ExcelMediaIcon />,
  },
  {
    filename: "Icon/file/word-media",
    name: "word-media",
    type: "Media",
    svg: <Icons.WordMediaIcon />,
  },
  {
    filename: "Icon/file/pdf-media",
    name: "pdf-media",
    type: "Media",
    svg: <Icons.PDFMediaIcon />,
  },

  // LEGACY Generic Icons
  {
    filename: "agency-icon/dosm",
    name: "dosm",
    type: "Legacy: Generic",
    svg: <Icons.DOSMIcon />,
  },
  {
    filename: "agency-icon/identity-jpn",
    name: "identity-jpn",
    type: "Legacy: Generic",
    svg: <Icons.IdentityJPNIcon />,
  },
  {
    filename: "agency-icon/car-jpj",
    name: "car-jpj",
    type: "Legacy: Generic",
    svg: <Icons.CarJPJIcon />,
  },
  {
    filename: "agency-icon/book-moe",
    name: "book-moe",
    type: "Legacy: Generic",
    svg: <Icons.BookMOEIcon />,
  },
  {
    filename: "agency-icon/internet-mcmc",
    name: "internet-mcmc",
    type: "Legacy: Generic",
    svg: <Icons.InternetMCMCIcon />,
  },
  {
    filename: "agency-icon/money-kwap",
    name: "money-kwap",
    type: "Legacy: Generic",
    svg: <Icons.MoneyKWAPIcon />,
  },
  {
    filename: "agency-icon/helmet-jpa",
    name: "helmet-jpa",
    type: "Legacy: Generic",
    svg: <Icons.HelmetJPAIcon />,
  },
  {
    filename: "agency-icon/train-mot",
    name: "train-mot",
    type: "Legacy: Generic",
    svg: <Icons.TrainMOTIcon />,
  },
  {
    filename: "agency-icon/unhcr",
    name: "unhcr",
    type: "Legacy: Generic",
    svg: <Icons.UNHCRIcon />,
  },
  {
    filename: "agency-icon/ribbon-ntrc",
    name: "ribbon-ntrc",
    type: "Legacy: Generic",
    svg: <Icons.RibbonNTRCIcon />,
  },
  {
    filename: "agency-icon/weather-met",
    name: "weather-met",
    type: "Legacy: Generic",
    svg: <Icons.WeatherMETIcon />,
  },
  {
    filename: "agency-icon/flood-jps",
    name: "flood-jps",
    type: "Legacy: Generic",
    svg: <Icons.FloodJPSIcon />,
  },
  {
    filename: "agency-icon/jakoa",
    name: "jakoa",
    type: "Legacy: Generic",
    svg: <Icons.JAKOAIcon />,
  },
  {
    filename: "agency-icon/blood-pdn",
    name: "blood-pdn",
    type: "Legacy: Generic",
    svg: <Icons.BloodPDNIcon />,
  },
  {
    filename: "agency-icon/ballot-spr",
    name: "ballot-spr",
    type: "Legacy: Generic",
    svg: <Icons.BallotSPRIcon />,
  },
  {
    filename: "agency-icon/fire-bomba",
    name: "fire-bomba",
    type: "Legacy: Generic",
    svg: <Icons.FireBOMBAIcon />,
  },
  {
    filename: "agency-icon/ambulance-mers",
    name: "ambulance-mers",
    type: "Legacy: Generic",
    svg: <Icons.AmbulanceMERSIcon />,
  },
  {
    filename: "agency-icon/hospital-moh",
    name: "hospital-moh",
    type: "Legacy: Generic",
    svg: <Icons.HospitalMOHIcon />,
  },
  {
    filename: "agency-icon/phcorp",
    name: "phcorp",
    type: "Legacy: Generic",
    svg: <Icons.PhcorpIcon />,
  },
  {
    filename: "agency-icon/passport-imigresen",
    name: "passport-imigresen",
    type: "Legacy: Generic",
    svg: <Icons.PassportImigresenIcon />,
  },
  {
    filename: "agency-icon/bnm",
    name: "bnm",
    type: "Legacy: Generic",
    svg: <Icons.BNMIcon />,
  },
  {
    filename: "agency-icon/money-epf",
    name: "money-epf",
    type: "Legacy: Generic",
    svg: <Icons.MoneyEPFIcon />,
  },
  {
    filename: "agency-icon/money-lhdn",
    name: "money-lhdn",
    type: "Legacy: Generic",
    svg: <Icons.MoneyLHDNIcon />,
  },
  {
    filename: "agency-icon/mampu",
    name: "mampu",
    type: "Legacy: Generic",
    svg: <Icons.MAMPUIcon />,
  },
  {
    filename: "agency-icon/socso-perkeso",
    name: "socso-perkeso",
    type: "Legacy: Generic",
    svg: <Icons.SOCSOPERKESOIcon />,
  },
  {
    filename: "agency-icon/light-bulb-ipr-epu",
    name: "light-bulb-ipr-epu",
    type: "Legacy: Generic",
    svg: <Icons.LightBulbIPREPUIcon />,
  },
  {
    filename: "agency-icon/police-pdrm",
    name: "police-pdrm",
    type: "Legacy: Generic",
    svg: <Icons.PolicePDRMIcon />,
  },
  {
    filename: "agency-icon/helping-hand-icu-jpm",
    name: "helping-hand-icu-jpm",
    type: "Legacy: Generic",
    svg: <Icons.HelpingHandICUJPMIcon />,
  },
  {
    filename: "agency-icon/document-mof",
    name: "document-mof",
    type: "Legacy: Generic",
    svg: <Icons.DocumentMOFIcon />,
  },

  // Without Round Shape or Borderless
  {
    filename: "agency-icon/phcorp",
    name: "phcorp",
    type: "Legacy: Borderless",
    svg: <Icons.MiniPhcorpIcon />,
  },
  {
    filename: "agency-icon/mampu",
    name: "mampu",
    type: "Legacy: Borderless",
    svg: <Icons.MiniMAMPUIcon />,
  },
  {
    filename: "agency-icon/ribbon-ntrc",
    name: "ribbon-ntrc",
    type: "Legacy: Borderless",
    svg: <Icons.MiniRibbonNTRCIcon />,
  },
  {
    filename: "agency-icon/bnm",
    name: "bnm",
    type: "Legacy: Borderless",
    svg: <Icons.MiniBNMIcon />,
  },
  {
    filename: "agency-icon/dosm",
    name: "dosm",
    type: "Legacy: Borderless",
    svg: <Icons.MiniDOSMIcon />,
  },
  {
    filename: "agency-icon/helmet-jpa",
    name: "helmet-jpa",
    type: "Legacy: Borderless",
    svg: <Icons.MiniHelmetJPAIcon />,
  },
  {
    filename: "agency-icon/document-mof",
    name: "document-mof",
    type: "Legacy: Borderless",
    svg: <Icons.MiniDocumentMOFIcon />,
  },
  {
    filename: "agency-icon/train-mot",
    name: "train-mot",
    type: "Legacy: Borderless",
    svg: <Icons.MiniTrainMOTIcon />,
  },
  {
    filename: "agency-icon/ambulance-mers",
    name: "ambulance-mers",
    type: "Legacy: Borderless",
    svg: <Icons.MiniAmbulanceMERSIcon />,
  },
  {
    filename: "agency-icon/hospital-moh",
    name: "hospital-moh",
    type: "Legacy: Borderless",
    svg: <Icons.MiniHospitalMOHIcon />,
  },
  {
    filename: "agency-icon/police-pdrm",
    name: "police-pdrm",
    type: "Legacy: Borderless",
    svg: <Icons.MiniPolicePDRMIcon />,
  },
  {
    filename: "agency-icon/weather-climate",
    name: "weather-climate",
    type: "Legacy: Borderless",
    svg: <Icons.MiniWeatherClimateIcon />,
  },
  {
    filename: "agency-icon/fire-bomba",
    name: "fire-bomba",
    type: "Legacy: Borderless",
    svg: <Icons.MiniFireBOMBAIcon />,
  },
  {
    filename: "agency-icon/flood-warning",
    name: "flood-warning",
    type: "Legacy: Borderless",
    svg: <Icons.MiniFloodWarningIcon />,
  },
  {
    filename: "agency-icon/light-bulb-ipr-epu",
    name: "light-bulb-ipr-epu",
    type: "Legacy: Borderless",
    svg: <Icons.MiniLightBulbIPREPUIcon />,
  },
  {
    filename: "agency-icon/helping-hands-icu-jpm",
    name: "helping-hands-icu-jpm",
    type: "Legacy: Borderless",
    svg: <Icons.MiniHelpingHandsICUJPMIcon />,
  },
  {
    filename: "agency-icon/money-kwap",
    name: "money-kwap",
    type: "Legacy: Borderless",
    svg: <Icons.MiniMoneyKWAPIcon />,
  },
  {
    filename: "agency-icon/ballot-spr",
    name: "ballot-spr",
    type: "Legacy: Borderless",
    svg: <Icons.MiniBallotSPRIcon />,
  },
  {
    filename: "agency-icon/money-epf",
    name: "money-epf",
    type: "Legacy: Borderless",
    svg: <Icons.MiniMoneyEPFIcon />,
  },
  {
    filename: "agency-icon/book-moe",
    name: "book-moe",
    type: "Legacy: Borderless",
    svg: <Icons.MiniBookMOEIcon />,
  },
  {
    filename: "agency-icon/passport-imigresen",
    name: "passport-imigresen",
    type: "Legacy: Borderless",
    svg: <Icons.MiniPassportImigresenIcon />,
  },
  {
    filename: "agency-icon/internet-mcmc",
    name: "internet-mcmc",
    type: "Legacy: Borderless",
    svg: <Icons.MiniInternetMCMCIcon />,
  },
  {
    filename: "agency-icon/blood-pdn",
    name: "blood-pdn",
    type: "Legacy: Borderless",
    svg: <Icons.MiniBloodPDNIcon />,
  },
  {
    filename: "agency-icon/car-jpj",
    name: "car-jpj",
    type: "Legacy: Borderless",
    svg: <Icons.MiniCarJPJIcon />,
  },
  {
    filename: "agency-icon/identity-jpn",
    name: "identity-jpn",
    type: "Legacy: Borderless",
    svg: <Icons.MiniIdentityJPNIcon />,
  },
  {
    filename: "agency-icon/socsco",
    name: "socso",
    type: "Legacy: Borderless",
    svg: <Icons.MiniSOCSOIcon />,
  },
  {
    filename: "agency-icon/money-lhdn",
    name: "money-lhdn",
    type: "Legacy: Borderless",
    svg: <Icons.MiniMoneyLHDNIcon />,
  },
  {
    filename: "agency-icon/unhcr",
    name: "unhcr",
    type: "Legacy: Borderless",
    svg: <Icons.MiniUNHCRIcon />,
  },
  {
    filename: "agency-icon/jakoa",
    name: "jakoa",
    type: "Legacy: Borderless",
    svg: <Icons.MiniJAKOAIcon />,
  },
  {
    filename: "agency-icon/website",
    name: "website",
    type: "Legacy: Borderless",
    svg: <Icons.MiniWebsiteIcon />,
  },
];
